#!bin/bash

# I build this project and run the server on the configuration
# file that should be generated by other bash scripts.

. util_scripts/remove_core_objbin.sh
dotnet run run .test_config.json